/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as KubernetesRouteImport } from './routes/kubernetes'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GithubRouteImport } from './routes/github'
import { Route as FetcherRouteImport } from './routes/fetcher'
import { Route as DockerRouteImport } from './routes/docker'
import { Route as GithubOrgRepoRouteImport } from './routes/github.$org.$repo'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const KubernetesRoute = KubernetesRouteImport.update({
  id: '/kubernetes',
  path: '/kubernetes',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const FetcherRoute = FetcherRouteImport.update({
  id: '/fetcher',
  path: '/fetcher',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerRoute = DockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubOrgRepoRoute = GithubOrgRepoRouteImport.update({
  id: '/$org/$repo',
  path: '/$org/$repo',
  getParentRoute: () => GithubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/docker': typeof DockerRoute
  '/fetcher': typeof FetcherRoute
  '/github': typeof GithubRouteWithChildren
  '/health': typeof HealthRoute
  '/kubernetes': typeof KubernetesRoute
  '/novedades': typeof NovedadesRoute
  '/setup': typeof SetupRoute
  '/github/$org/$repo': typeof GithubOrgRepoRoute
}
export interface FileRoutesByTo {
  '/docker': typeof DockerRoute
  '/fetcher': typeof FetcherRoute
  '/github': typeof GithubRouteWithChildren
  '/health': typeof HealthRoute
  '/kubernetes': typeof KubernetesRoute
  '/novedades': typeof NovedadesRoute
  '/setup': typeof SetupRoute
  '/github/$org/$repo': typeof GithubOrgRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/docker': typeof DockerRoute
  '/fetcher': typeof FetcherRoute
  '/github': typeof GithubRouteWithChildren
  '/health': typeof HealthRoute
  '/kubernetes': typeof KubernetesRoute
  '/novedades': typeof NovedadesRoute
  '/setup': typeof SetupRoute
  '/github/$org/$repo': typeof GithubOrgRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/docker'
    | '/fetcher'
    | '/github'
    | '/health'
    | '/kubernetes'
    | '/novedades'
    | '/setup'
    | '/github/$org/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docker'
    | '/fetcher'
    | '/github'
    | '/health'
    | '/kubernetes'
    | '/novedades'
    | '/setup'
    | '/github/$org/$repo'
  id:
    | '__root__'
    | '/docker'
    | '/fetcher'
    | '/github'
    | '/health'
    | '/kubernetes'
    | '/novedades'
    | '/setup'
    | '/github/$org/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DockerRoute: typeof DockerRoute
  FetcherRoute: typeof FetcherRoute
  GithubRoute: typeof GithubRouteWithChildren
  HealthRoute: typeof HealthRoute
  KubernetesRoute: typeof KubernetesRoute
  NovedadesRoute: typeof NovedadesRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kubernetes': {
      id: '/kubernetes'
      path: '/kubernetes'
      fullPath: '/kubernetes'
      preLoaderRoute: typeof KubernetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetcher': {
      id: '/fetcher'
      path: '/fetcher'
      fullPath: '/fetcher'
      preLoaderRoute: typeof FetcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker': {
      id: '/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof DockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/$org/$repo': {
      id: '/github/$org/$repo'
      path: '/$org/$repo'
      fullPath: '/github/$org/$repo'
      preLoaderRoute: typeof GithubOrgRepoRouteImport
      parentRoute: typeof GithubRoute
    }
  }
}

interface GithubRouteChildren {
  GithubOrgRepoRoute: typeof GithubOrgRepoRoute
}

const GithubRouteChildren: GithubRouteChildren = {
  GithubOrgRepoRoute: GithubOrgRepoRoute,
}

const GithubRouteWithChildren =
  GithubRoute._addFileChildren(GithubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DockerRoute: DockerRoute,
  FetcherRoute: FetcherRoute,
  GithubRoute: GithubRouteWithChildren,
  HealthRoute: HealthRoute,
  KubernetesRoute: KubernetesRoute,
  NovedadesRoute: NovedadesRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
